name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
    
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip build-essential git zip unzip
        pip3 install --upgrade pip
        pip3 install buildozer cython==0.29.33
    
    - name: Create buildozer.spec
      run: |
        cat > buildozer.spec << 'EOF'
        [app]
        title = Snake Game
        package.name = snakegame
        package.domain = org.example
        source.dir = .
        source.include_exts = py,png,jpg,kv,atlas
        version = 1.0
        requirements = python3,kivy
        
        [buildozer]
        log_level = 2
        
        [app:android]
        android.api = 28
        android.minapi = 21
        android.ndk = 19b
        android.sdk = 28
        android.debug = 1
        android.accept_sdk_license = True
        EOF
    
    - name: Build APK
      run: |
        export ANDROIDSDK=$ANDROID_SDK_ROOT
        buildozer android debug
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: snake-game-apk
        path: bin/*.apk
