name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: kivy/buildozer:latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Create buildozer.spec
      run: |
        cat > buildozer.spec << 'EOF'
        [app]
        title = Snake Game
        package.name = snakegame
        package.domain = org.example
        source.dir = .
        source.include_exts = py,png,jpg,kv,atlas
        version = 1.0
        requirements = python3,kivy
        
        [buildozer]
        log_level = 2
        
        [app:android]
        android.api = 28
        android.minapi = 21
        android.ndk = 19b
        android.sdk = 28
        android.permissions = INTERNET
        android.debug = 1
        android.accept_sdk_license = True
        EOF
    
    - name: Build APK
      run: buildozer android debug
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: snake-game-apk
        path: bin/*.apk
