name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    
    - name: Install Android SDK
      uses: android-actions/setup-android@v3
      with:
        api-level: 29
        build-tools: 29.0.3
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip python3-setuptools git zip unzip openjdk-11-jdk python3-dev build-essential libssl-dev libffi-dev libxml2-dev libxslt1-dev libjpeg8-dev zlib1g-dev
    
    - name: Install Python dependencies
      run: |
        pip3 install --user --upgrade Cython==0.29.33 virtualenv
        pip3 install --user buildozer
    
    - name: Create buildozer.spec
      run: |
        cat > buildozer.spec << 'EOF'
        [app]
        title = Snake Game
        package.name = snakegame
        package.domain = org.example
        source.dir = .
        source.include_exts = py,png,jpg,kv,atlas
        version = 1.0
        requirements = python3,kivy
        
        [buildozer]
        log_level = 2
        
        [app:android]
        android.api = 29
        android.minapi = 21
        android.ndk = 21e
        android.sdk = 29
        android.permissions = INTERNET
        android.debug = 1
        android.accept_sdk_license = True
        EOF
    
    - name: Accept SDK licenses
      run: |
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
    
    - name: Build APK
      run: |
        export PATH=$PATH:~/.local/bin
        buildozer android debug
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: snake-game-apk
        path: bin/*.apk
